#!/usr/bin/env bash

export PATH=/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

ruby -v

# Assume dotfiles was cloned to ~/.dotfiles
pushd $HOME

# Symlink dotfiles

dotfiles=(
  .bash_profile
  .git-completion.bash
  .git-prompt.sh
  .gitconfig
  .gitignore
  .gitignore_global
  .gitmodules
  .gvimrc
  .rspec
  .tigrc
  .tmux
  .tmux.conf
  .tmuxinator
  .vim
  .vimrc
)

for dotfile in "${dotfiles[@]}"; do
  ln -s .dotfiles/$dotfile $dotfile
done

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

pushd .dotfiles

# Install brews and casks
brew tap Homebrew/bundle
brew bundle

# Install crontab
crontab ./crontab

popd

# Install rbenv
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv

# Prep rbenv for immediate use
export PATH=$HOME/.rbenv/bin:$PATH
eval "$(rbenv init -)"

# Install a recent'ish version of ruby
rbenv install 2.2.2
rbenv global 2.2.2
rbenv rehash
source ~/.bash_profile # to get the new ruby in PATH

# Initialise vim plugins
pushd .vim
git submodule init
git submodule update

# Compile C extension for command-t
pushd bundle/command-t/ruby/command-t/
ruby extconf.rb
make
