#!/usr/bin/env bash

export PATH=/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

ruby -v

# Assume dotfiles was cloned to ~/.dotfiles
pushd $HOME

# Symlink dotfiles

dotfiles=(
  .bash_profile
  .git-completion.bash
  .git-prompt.sh
  .gitconfig
  .gitignore
  .gitignore_global
  .gitmodules
  .gvimrc
  .rspec
  .tigrc
  .tmux
  .tmux.conf
  .tmuxinator
  .vim
  .vimrc
  .gdbinit
  .jrnl_config
)

for dotfile in "${dotfiles[@]}"; do
  ln -s .dotfiles/$dotfile $dotfile
done

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

pushd .dotfiles

# Install brews and casks
brew tap Homebrew/bundle
brew bundle

# Install crontab
echo 'Installing crontab, this might require security confirmation'
crontab ./crontab

popd

# Add Material Design colour palette to Inkscape
mkdir -p ~/.config/inkscape/palettes/
pushd ~/.config/inkscape/palettes/

curl -O https://raw.githubusercontent.com/KiSSFLOW/gimp-material-design-color-palette/master/Material-Design.gpl

popd

# Install rbenv
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv

# Prep rbenv for immediate use
export PATH=$HOME/.rbenv/bin:$PATH
eval "$(rbenv init -)"

# Install latest version of ruby
ruby_version=$(curl https://www.ruby-lang.org/en/downloads/ | \
  grep "The current stable version is" | \
  sed -e "s/The current stable version is \(.*\).$"/\\1/g)

rbenv install $ruby_version
rbenv global $ruby_version
rbenv rehash
source ~/.bash_profile # to get the new ruby in PATH

# Initialise vim plugins
pushd .vim
git submodule init
git submodule update

# Compile C extension for command-t
pushd bundle/command-t/ruby/command-t/
ruby extconf.rb
make

echo "Changing screenshot destination folder..."
# Change screenshot destination folder
defaults write com.apple.screencapture location ~/Downloads
killall SystemUIServer

# Add jrnl symlink
ln -s ~/Dropbox/jrnl ~/.jrnl
