tap 'caskroom/cask'

brew 'bmon'
brew 'cloc'
brew 'ctags'
brew 'curl'
brew 'ffmpeg'
brew 'docker-compose'
brew 'gcc'
brew 'git'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnupg'
brew 'imagemagick'
brew 'nmap'
brew 'openssl'
brew 'pbzip2'
brew 'reattach-to-user-namespace'
brew 'renameutils'
brew 'ruby-build'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'unrar'
brew 'vim'
brew 'watch'
brew 'wget'
brew 'node'
brew 'ncdu'             # shows disk usage

cask 'caffeine'
cask 'cyberduck'
cask 'disk-inventory-x' # shows disk usage
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'heroku-toolbelt'
cask 'imageoptim'
cask 'inkscape'
cask 'karabiner'        # enable option "F19 for Escape and Control"
cask 'libreoffice'
cask 'macdown'
cask 'moom'
cask 'postgres'
cask 'seil'             # bind capslock to 53 as ESC
cask 'skype'
cask 'torbrowser'
cask 'transmission'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'vmware-fusion'
cask 'wireshark'
cask 'xquartz'
cask 'docker'
