---
- name: Check if Homebrew is installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: Install Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not homebrew_check.stat.exists

- name: Install Homebrew packages
  community.general.homebrew:
    path:  "{{ ansible_env.HOME }}/.dotfiles/darwin/Brewfile"
    state: present
