---
- name: Create symlinks for dotfiles
  file:
    src: "{{ dotfiles_dir }}/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: yes
  loop:
    - .zshrc
    - .p10k.zsh
    - .gitconfig
    - .tigrc
    - .tmux
    - .tmux.conf

# zsh

- name: Install oh-my-zsh
  ansible.builtin.shell: >
    curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Clone zsh plugins theme & plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    depth: 1
  loop:
    - repo: https://github.com/romkatv/powerlevel10k.git
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    - repo: https://github.com/zsh-users/zsh-autosuggestions.git
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    - repo: https://github.com/MichaelAquilina/zsh-you-should-use.git
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/you-should-use"

# misc.
- name: Clone asdf version manager
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ ansible_env.HOME }}/.asdf"
    version: v0.14.1
