---
- name: Create symlinks for dotfiles
  file:
    src: "{{ dotfiles_dir }}/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: yes
  loop:
    - .zshrc
    - .gitconfig
    - .tigrc
    - .tmux
    - .tmux.conf

- name: Install oh-my-zsh
  ansible.builtin.shell: >
    curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
