---
- name: Create symlinks for dotfiles
  file:
    src: "{{ dotfiles_dir }}/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: yes
  loop:
    - .zshrc
    - .p10k.zsh
    - .gitconfig
    - .tigrc
    - .tmux
    - .tmux.conf

- name: Install oh-my-zsh
  ansible.builtin.shell: >
    curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Clone Powerlevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1

- name: Clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    depth: 1

- name: Clone zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1

- name: Clone you-should-use
  git:
    repo: https://github.com/MichaelAquilina/zsh-you-should-use.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/you-should-use"
    depth: 1
