---
# Zsh

- name: Install oh-my-zsh
  ansible.builtin.shell: >
    curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Clone zsh plugins theme & plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    depth: 1
  loop:
    - repo: https://github.com/romkatv/powerlevel10k.git
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    - repo: https://github.com/zsh-users/zsh-autosuggestions.git
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    - repo: https://github.com/MichaelAquilina/zsh-you-should-use.git
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/you-should-use"

- name: Create symlinks for dotfiles
  file:
    src: "{{ dotfiles_dir }}/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: yes
  loop:
    - .gitconfig
    - .gitignore_global
    - .p10k.zsh
    - .tigrc
    - .tmux
    - .tmux.conf
    - .zshrc

# create ~/.config if it doesn't already exist
- name: Create .config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory

- name: Create symlinks for shared configs
  file:
    src: "{{ dotfiles_dir }}/.config/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: link
    force: yes
  loop:
    - jrnl
    - nvim

# Misc.

- name: Clone asdf version manager
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ ansible_env.HOME }}/.asdf"
    version: v0.14.1

- name: Display Dropbox installation instructions
  debug:
    msg: |
      =====================================================
      NEXT STEPS - Install Dropbox and Configure jrnl:
      
      1. Install Dropbox:
         Visit: https://www.dropbox.com/install
         Follow the installation instructions for your system
      
      2. After Dropbox is installed and configured, create the symlink:
         ln -s ~/Path/To/Dropbox/jrnl ~/.jrnl
      
      This will make the different jrnl files available and synced to other
      computers.
      =====================================================
  run_once: true
  delegate_to: localhost
