---
- name: Create symlinks for dotfiles
  file:
    src: "{{ dotfiles_dir }}/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: yes
  loop:
    - .zsh_aliases
    - .zshrc
    - .gitconfig
    - .tigrc
    - .tmux
    - .tmux.conf
